### PR TITLE
[ADD] estate: Create base files and first model T#72976

### PR DESCRIPTION
**Pull request by gerashdo**
- Create base files `__init__.py` and `__manifest__.py` for `estate` application. Link to the exercise: https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/03_newapp.html

- Creation of the first model `estate.property`, including its base fields. Link to the exercise: https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/04_basicmodel.html

### CODE REVIEW

**Comment by gerashdo** [comment]
Ready for review. Please check it out @JesusValdez96

**Comment by gerashdo** [comment]
Changes made. Ready for review @JesusValdez96

**Comment by JesusValdez96** [comment]
Hi @gerashdo add .bandit to gitignore

**Comment by gerashdo** [comment]
@JesusValdez96 Done! 🙃. Ready for review.

**Review by JesusValdez96 — APPROVED** [review]

**Pull request merged**
